In [1]:
import pandas as pd

In [2]:
#import pandas as pd
# Save file path to variable
happiness_csv = "Resources/datasets_669650_1179076_Happiness.csv"
# Read with Pandas
happy_df = pd.read_csv(happiness_csv)
happy_df.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [3]:
economic_csv = "Resources/datasets_127094_304788_economic_freedom_index2019_data.csv"
econ_df = pd.read_csv(economic_csv, encoding='ISO-8859-1')
econ_df.head()

,CountryID,Country Name,WEBNAME,Region,World Rank,Region Rank,2019 Score,Property Rights,Judical Effectiveness,Government Integrity,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
0,1,Afghanistan,Afghanistan,Asia-Pacific,152.0,39.0,51.5,19.6,29.6,25.2,...,Afghanistan,35.5,$69.60,2.5,2.9,"$1,958",8.8,5.0,53.9,7.3
1,2,Albania,Albania,Europe,52.0,27.0,66.5,54.8,30.6,40.4,...,Albania,2.9,$36.00,3.9,2.5,"$12,507",13.9,2.0,"1,119.10",71.2
2,3,Algeria,Algeria,Middle East and North Africa,171.0,14.0,46.2,31.6,36.2,28.9,...,Algeria,41.5,$632.90,2.0,3.1,"$15,237",10,5.6,"1,203.00",25.8
3,4,Angola,Angola,Sub-Saharan Africa,156.0,33.0,50.6,35.9,26.6,20.5,...,Angola,28.2,$190.30,0.7,2.9,"$6,753",8.2,31.7,"-2,254.50",65.3
4,5,Argentina,Argentina,Americas,148.0,26.0,52.2,47.8,44.5,33.5,...,Argentina,44.1,$920.20,2.9,0.7,"$20,876",8.7,25.7,"11,857.00",52.6

In [5]:
econ_cols = ["Country Name", "2019 Score", "Property Rights", "Judical Effectiveness", "Government Integrity", 
             "Population (Millions)", "GDP Growth Rate (%)", "GDP per Capita (PPP)", 
             "Unemployment (%)", "Inflation (%)", "Public Debt (% of GDP)"]
econ_transformed_df = econ_df[econ_cols].copy()
econ_transformed_df.rename(columns = {'Country Name': 'Country_Name', '2019 Score': '2019_Score', 
                                      'Property Rights': 'Property_Rights', 'Judical Effectiveness': 'Judicial_Effectiveness', 'Government Integrity': 'Government_Integrity',
                         'Population (Millions)': 'Population_Millions', 'GDP Growth Rate (%)': 'GDP_Growth_Rate_Percent',
                                     'GDP per Capita (PPP)': 'GDP_per_Capita_PPP', 
                                      'Unemployment (%)': 'Unemployment_Percent', 'Inflation (%)': 'Inflation_Percent',
                                     'Public Debt (% of GDP)': 'Public_Debt_Percent_of_GDP'}, inplace = True)


econ_transformed_df.head()

,Country_Name,2019_Score,Property_Rights,Judicial_Effectiveness,Government_Integrity,Population_Millions,GDP_Growth_Rate_Percent,GDP_per_Capita_PPP,Unemployment_Percent,Inflation_Percent,Public_Debt_Percent_of_GDP
0,Afghanistan,51.5,19.6,29.6,25.2,35.5,2.5,"$1,958",8.8,5.0,7.3
1,Albania,66.5,54.8,30.6,40.4,2.9,3.9,"$12,507",13.9,2.0,71.2
2,Algeria,46.2,31.6,36.2,28.9,41.5,2.0,"$15,237",10,5.6,25.8
3,Angola,50.6,35.9,26.6,20.5,28.2,0.7,"$6,753",8.2,31.7,65.3
4,Argentina,52.2,47.8,44.5,33.5,44.1,2.9,"$20,876",8.7,25.7,52.6